<?xml version="1.0" encoding="utf-8"?><Database Name="SGPAPI" Class="SGPAPIDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.0.10.10;Initial Catalog=SGPAPI;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SGPAPIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PMS_MaxMailerID" Member="PMS_MaxMailerIDs">
    <Type Name="PMS_MaxMailerID">
      <Column Name="PostOfficeID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaxID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>