#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPWebService.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SGPAPI")]
	public partial class SGPAPIDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPMS_MaxMailerID(PMS_MaxMailerID instance);
    partial void UpdatePMS_MaxMailerID(PMS_MaxMailerID instance);
    partial void DeletePMS_MaxMailerID(PMS_MaxMailerID instance);
    partial void InsertSGP_Province_Zone(SGP_Province_Zone instance);
    partial void UpdateSGP_Province_Zone(SGP_Province_Zone instance);
    partial void DeleteSGP_Province_Zone(SGP_Province_Zone instance);
    partial void InsertSGP_Price_Customer(SGP_Price_Customer instance);
    partial void UpdateSGP_Price_Customer(SGP_Price_Customer instance);
    partial void DeleteSGP_Price_Customer(SGP_Price_Customer instance);
    partial void InsertSGP_Price_Service(SGP_Price_Service instance);
    partial void UpdateSGP_Price_Service(SGP_Price_Service instance);
    partial void DeleteSGP_Price_Service(SGP_Price_Service instance);
    partial void InsertSGP_Price_Policy(SGP_Price_Policy instance);
    partial void UpdateSGP_Price_Policy(SGP_Price_Policy instance);
    partial void DeleteSGP_Price_Policy(SGP_Price_Policy instance);
    partial void InsertSGP_Price_Value(SGP_Price_Value instance);
    partial void UpdateSGP_Price_Value(SGP_Price_Value instance);
    partial void DeleteSGP_Price_Value(SGP_Price_Value instance);
    partial void InsertTools_Tracking(Tools_Tracking instance);
    partial void UpdateTools_Tracking(Tools_Tracking instance);
    partial void DeleteTools_Tracking(Tools_Tracking instance);
    partial void InsertSGP_Price_Service_Value(SGP_Price_Service_Value instance);
    partial void UpdateSGP_Price_Service_Value(SGP_Price_Service_Value instance);
    partial void DeleteSGP_Price_Service_Value(SGP_Price_Service_Value instance);
    partial void InsertSGP_SpecialCustomer(SGP_SpecialCustomer instance);
    partial void UpdateSGP_SpecialCustomer(SGP_SpecialCustomer instance);
    partial void DeleteSGP_SpecialCustomer(SGP_SpecialCustomer instance);
    partial void InsertSGP_CustomerWithZone(SGP_CustomerWithZone instance);
    partial void UpdateSGP_CustomerWithZone(SGP_CustomerWithZone instance);
    partial void DeleteSGP_CustomerWithZone(SGP_CustomerWithZone instance);
    partial void InsertSGP_ChiTietHoaDon(SGP_ChiTietHoaDon instance);
    partial void UpdateSGP_ChiTietHoaDon(SGP_ChiTietHoaDon instance);
    partial void DeleteSGP_ChiTietHoaDon(SGP_ChiTietHoaDon instance);
    partial void InsertSGP_HoaDon(SGP_HoaDon instance);
    partial void UpdateSGP_HoaDon(SGP_HoaDon instance);
    partial void DeleteSGP_HoaDon(SGP_HoaDon instance);
    partial void InsertSGP_CutomerGroup(SGP_CutomerGroup instance);
    partial void UpdateSGP_CutomerGroup(SGP_CutomerGroup instance);
    partial void DeleteSGP_CutomerGroup(SGP_CutomerGroup instance);
    partial void InsertSGP_CustomerGroupDetail(SGP_CustomerGroupDetail instance);
    partial void UpdateSGP_CustomerGroupDetail(SGP_CustomerGroupDetail instance);
    partial void DeleteSGP_CustomerGroupDetail(SGP_CustomerGroupDetail instance);
    #endregion
		
		public SGPAPIDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SGPAPIConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SGPAPIDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SGPAPIDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SGPAPIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SGPAPIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PMS_MaxMailerID> PMS_MaxMailerIDs
		{
			get
			{
				return this.GetTable<PMS_MaxMailerID>();
			}
		}
		
		public System.Data.Linq.Table<SGP_Province_Zone> SGP_Province_Zones
		{
			get
			{
				return this.GetTable<SGP_Province_Zone>();
			}
		}
		
		public System.Data.Linq.Table<SGP_Price_Customer> SGP_Price_Customers
		{
			get
			{
				return this.GetTable<SGP_Price_Customer>();
			}
		}
		
		public System.Data.Linq.Table<SGP_Price_Service> SGP_Price_Services
		{
			get
			{
				return this.GetTable<SGP_Price_Service>();
			}
		}
		
		public System.Data.Linq.Table<SGP_Price_Policy> SGP_Price_Policies
		{
			get
			{
				return this.GetTable<SGP_Price_Policy>();
			}
		}
		
		public System.Data.Linq.Table<SGP_Price_Value> SGP_Price_Values
		{
			get
			{
				return this.GetTable<SGP_Price_Value>();
			}
		}
		
		public System.Data.Linq.Table<Tools_Tracking> Tools_Trackings
		{
			get
			{
				return this.GetTable<Tools_Tracking>();
			}
		}
		
		public System.Data.Linq.Table<SGP_Price_Service_Value> SGP_Price_Service_Values
		{
			get
			{
				return this.GetTable<SGP_Price_Service_Value>();
			}
		}
		
		public System.Data.Linq.Table<SGP_SpecialCustomer> SGP_SpecialCustomers
		{
			get
			{
				return this.GetTable<SGP_SpecialCustomer>();
			}
		}
		
		public System.Data.Linq.Table<SGP_CustomerWithZone> SGP_CustomerWithZones
		{
			get
			{
				return this.GetTable<SGP_CustomerWithZone>();
			}
		}
		
		public System.Data.Linq.Table<SGP_ChiTietHoaDon> SGP_ChiTietHoaDons
		{
			get
			{
				return this.GetTable<SGP_ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<SGP_HoaDon> SGP_HoaDons
		{
			get
			{
				return this.GetTable<SGP_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<SGP_CutomerGroup> SGP_CutomerGroups
		{
			get
			{
				return this.GetTable<SGP_CutomerGroup>();
			}
		}
		
		public System.Data.Linq.Table<SGP_CustomerGroupDetail> SGP_CustomerGroupDetails
		{
			get
			{
				return this.GetTable<SGP_CustomerGroupDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PMS_MaxMailerID")]
	public partial class PMS_MaxMailerID : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PostOfficeID;
		
		private string _MaxID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPostOfficeIDChanging(string value);
    partial void OnPostOfficeIDChanged();
    partial void OnMaxIDChanging(string value);
    partial void OnMaxIDChanged();
    #endregion
		
		public PMS_MaxMailerID()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOfficeID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PostOfficeID
		{
			get
			{
				return this._PostOfficeID;
			}
			set
			{
				if ((this._PostOfficeID != value))
				{
					this.OnPostOfficeIDChanging(value);
					this.SendPropertyChanging();
					this._PostOfficeID = value;
					this.SendPropertyChanged("PostOfficeID");
					this.OnPostOfficeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxID", DbType="NVarChar(20)")]
		public string MaxID
		{
			get
			{
				return this._MaxID;
			}
			set
			{
				if ((this._MaxID != value))
				{
					this.OnMaxIDChanging(value);
					this.SendPropertyChanging();
					this._MaxID = value;
					this.SendPropertyChanged("MaxID");
					this.OnMaxIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_Province_Zones")]
	public partial class SGP_Province_Zone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ZoneID;
		
		private string _ProvinceID;
		
		private System.Nullable<int> _Zone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZoneIDChanging(string value);
    partial void OnZoneIDChanged();
    partial void OnProvinceIDChanging(string value);
    partial void OnProvinceIDChanged();
    partial void OnZoneChanging(System.Nullable<int> value);
    partial void OnZoneChanged();
    #endregion
		
		public SGP_Province_Zone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ZoneID
		{
			get
			{
				return this._ZoneID;
			}
			set
			{
				if ((this._ZoneID != value))
				{
					this.OnZoneIDChanging(value);
					this.SendPropertyChanging();
					this._ZoneID = value;
					this.SendPropertyChanged("ZoneID");
					this.OnZoneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceID", DbType="NVarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProvinceID
		{
			get
			{
				return this._ProvinceID;
			}
			set
			{
				if ((this._ProvinceID != value))
				{
					this.OnProvinceIDChanging(value);
					this.SendPropertyChanging();
					this._ProvinceID = value;
					this.SendPropertyChanged("ProvinceID");
					this.OnProvinceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="Int")]
		public System.Nullable<int> Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this.OnZoneChanging(value);
					this.SendPropertyChanging();
					this._Zone = value;
					this.SendPropertyChanged("Zone");
					this.OnZoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_Price_Customer")]
	public partial class SGP_Price_Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PriceID;
		
		private string _CustomerID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPriceIDChanging(string value);
    partial void OnPriceIDChanged();
    partial void OnCustomerIDChanging(string value);
    partial void OnCustomerIDChanged();
    #endregion
		
		public SGP_Price_Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PriceID
		{
			get
			{
				return this._PriceID;
			}
			set
			{
				if ((this._PriceID != value))
				{
					this.OnPriceIDChanging(value);
					this.SendPropertyChanging();
					this._PriceID = value;
					this.SendPropertyChanged("PriceID");
					this.OnPriceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_Price_Service")]
	public partial class SGP_Price_Service : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PriceID;
		
		private string _ServiceID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPriceIDChanging(string value);
    partial void OnPriceIDChanged();
    partial void OnServiceIDChanging(string value);
    partial void OnServiceIDChanged();
    #endregion
		
		public SGP_Price_Service()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PriceID
		{
			get
			{
				return this._PriceID;
			}
			set
			{
				if ((this._PriceID != value))
				{
					this.OnPriceIDChanging(value);
					this.SendPropertyChanging();
					this._PriceID = value;
					this.SendPropertyChanged("PriceID");
					this.OnPriceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceID", DbType="NVarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ServiceID
		{
			get
			{
				return this._ServiceID;
			}
			set
			{
				if ((this._ServiceID != value))
				{
					this.OnServiceIDChanging(value);
					this.SendPropertyChanging();
					this._ServiceID = value;
					this.SendPropertyChanged("ServiceID");
					this.OnServiceIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_Price_Policy")]
	public partial class SGP_Price_Policy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PricePolicyID;
		
		private string _PostOfficeID;
		
		private string _Type;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _Service;
		
		private string _Description;
		
		private string _ZoneID;
		
		private string _CalPrice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPricePolicyIDChanging(string value);
    partial void OnPricePolicyIDChanged();
    partial void OnPostOfficeIDChanging(string value);
    partial void OnPostOfficeIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnServiceChanging(System.Nullable<int> value);
    partial void OnServiceChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnZoneIDChanging(string value);
    partial void OnZoneIDChanged();
    partial void OnCalPriceChanging(string value);
    partial void OnCalPriceChanged();
    #endregion
		
		public SGP_Price_Policy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricePolicyID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PricePolicyID
		{
			get
			{
				return this._PricePolicyID;
			}
			set
			{
				if ((this._PricePolicyID != value))
				{
					this.OnPricePolicyIDChanging(value);
					this.SendPropertyChanging();
					this._PricePolicyID = value;
					this.SendPropertyChanged("PricePolicyID");
					this.OnPricePolicyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOfficeID", DbType="NVarChar(4)")]
		public string PostOfficeID
		{
			get
			{
				return this._PostOfficeID;
			}
			set
			{
				if ((this._PostOfficeID != value))
				{
					this.OnPostOfficeIDChanging(value);
					this.SendPropertyChanging();
					this._PostOfficeID = value;
					this.SendPropertyChanged("PostOfficeID");
					this.OnPostOfficeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(1)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Service", DbType="Int")]
		public System.Nullable<int> Service
		{
			get
			{
				return this._Service;
			}
			set
			{
				if ((this._Service != value))
				{
					this.OnServiceChanging(value);
					this.SendPropertyChanging();
					this._Service = value;
					this.SendPropertyChanged("Service");
					this.OnServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneID", DbType="NVarChar(10)")]
		public string ZoneID
		{
			get
			{
				return this._ZoneID;
			}
			set
			{
				if ((this._ZoneID != value))
				{
					this.OnZoneIDChanging(value);
					this.SendPropertyChanging();
					this._ZoneID = value;
					this.SendPropertyChanged("ZoneID");
					this.OnZoneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalPrice", DbType="NVarChar(50)")]
		public string CalPrice
		{
			get
			{
				return this._CalPrice;
			}
			set
			{
				if ((this._CalPrice != value))
				{
					this.OnCalPriceChanging(value);
					this.SendPropertyChanging();
					this._CalPrice = value;
					this.SendPropertyChanged("CalPrice");
					this.OnCalPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_Price_Value")]
	public partial class SGP_Price_Value : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PriceID;
		
		private double _FW;
		
		private double _TW;
		
		private int _Zone;
		
		private System.Nullable<double> _Price;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<int> _RowIndex;
		
		private System.Nullable<int> _ColumnIndex;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPriceIDChanging(string value);
    partial void OnPriceIDChanged();
    partial void OnFWChanging(double value);
    partial void OnFWChanged();
    partial void OnTWChanging(double value);
    partial void OnTWChanged();
    partial void OnZoneChanging(int value);
    partial void OnZoneChanged();
    partial void OnPriceChanging(System.Nullable<double> value);
    partial void OnPriceChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnRowIndexChanging(System.Nullable<int> value);
    partial void OnRowIndexChanged();
    partial void OnColumnIndexChanging(System.Nullable<int> value);
    partial void OnColumnIndexChanged();
    #endregion
		
		public SGP_Price_Value()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PriceID
		{
			get
			{
				return this._PriceID;
			}
			set
			{
				if ((this._PriceID != value))
				{
					this.OnPriceIDChanging(value);
					this.SendPropertyChanging();
					this._PriceID = value;
					this.SendPropertyChanged("PriceID");
					this.OnPriceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FW", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double FW
		{
			get
			{
				return this._FW;
			}
			set
			{
				if ((this._FW != value))
				{
					this.OnFWChanging(value);
					this.SendPropertyChanging();
					this._FW = value;
					this.SendPropertyChanged("FW");
					this.OnFWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TW", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double TW
		{
			get
			{
				return this._TW;
			}
			set
			{
				if ((this._TW != value))
				{
					this.OnTWChanging(value);
					this.SendPropertyChanging();
					this._TW = value;
					this.SendPropertyChanged("TW");
					this.OnTWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this.OnZoneChanging(value);
					this.SendPropertyChanging();
					this._Zone = value;
					this.SendPropertyChanged("Zone");
					this.OnZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowIndex", DbType="Int")]
		public System.Nullable<int> RowIndex
		{
			get
			{
				return this._RowIndex;
			}
			set
			{
				if ((this._RowIndex != value))
				{
					this.OnRowIndexChanging(value);
					this.SendPropertyChanging();
					this._RowIndex = value;
					this.SendPropertyChanged("RowIndex");
					this.OnRowIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnIndex", DbType="Int")]
		public System.Nullable<int> ColumnIndex
		{
			get
			{
				return this._ColumnIndex;
			}
			set
			{
				if ((this._ColumnIndex != value))
				{
					this.OnColumnIndexChanging(value);
					this.SendPropertyChanging();
					this._ColumnIndex = value;
					this.SendPropertyChanged("ColumnIndex");
					this.OnColumnIndexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tools_Trackings")]
	public partial class Tools_Tracking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ColumnID;
		
		private string _Columnname;
		
		private System.Nullable<int> _IsCheck;
		
		private string _UserName;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnColumnIDChanging(string value);
    partial void OnColumnIDChanged();
    partial void OnColumnnameChanging(string value);
    partial void OnColumnnameChanged();
    partial void OnIsCheckChanging(System.Nullable<int> value);
    partial void OnIsCheckChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Tools_Tracking()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ColumnID
		{
			get
			{
				return this._ColumnID;
			}
			set
			{
				if ((this._ColumnID != value))
				{
					this.OnColumnIDChanging(value);
					this.SendPropertyChanging();
					this._ColumnID = value;
					this.SendPropertyChanged("ColumnID");
					this.OnColumnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Columnname", DbType="NVarChar(50)")]
		public string Columnname
		{
			get
			{
				return this._Columnname;
			}
			set
			{
				if ((this._Columnname != value))
				{
					this.OnColumnnameChanging(value);
					this.SendPropertyChanging();
					this._Columnname = value;
					this.SendPropertyChanged("Columnname");
					this.OnColumnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCheck", DbType="Int")]
		public System.Nullable<int> IsCheck
		{
			get
			{
				return this._IsCheck;
			}
			set
			{
				if ((this._IsCheck != value))
				{
					this.OnIsCheckChanging(value);
					this.SendPropertyChanging();
					this._IsCheck = value;
					this.SendPropertyChanged("IsCheck");
					this.OnIsCheckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_Price_Service_Value")]
	public partial class SGP_Price_Service_Value : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PriceID;
		
		private string _Service;
		
		private int _PercentOnPrice;
		
		private double _ConditionApply;
		
		private double _Weight;
		
		private int _Zone;
		
		private System.Nullable<double> _Price;
		
		private System.Nullable<int> _RowIndex;
		
		private System.Nullable<int> _ColumnIndex;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPriceIDChanging(string value);
    partial void OnPriceIDChanged();
    partial void OnServiceChanging(string value);
    partial void OnServiceChanged();
    partial void OnPercentOnPriceChanging(int value);
    partial void OnPercentOnPriceChanged();
    partial void OnConditionApplyChanging(double value);
    partial void OnConditionApplyChanged();
    partial void OnWeightChanging(double value);
    partial void OnWeightChanged();
    partial void OnZoneChanging(int value);
    partial void OnZoneChanged();
    partial void OnPriceChanging(System.Nullable<double> value);
    partial void OnPriceChanged();
    partial void OnRowIndexChanging(System.Nullable<int> value);
    partial void OnRowIndexChanged();
    partial void OnColumnIndexChanging(System.Nullable<int> value);
    partial void OnColumnIndexChanged();
    #endregion
		
		public SGP_Price_Service_Value()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PriceID
		{
			get
			{
				return this._PriceID;
			}
			set
			{
				if ((this._PriceID != value))
				{
					this.OnPriceIDChanging(value);
					this.SendPropertyChanging();
					this._PriceID = value;
					this.SendPropertyChanged("PriceID");
					this.OnPriceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Service", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Service
		{
			get
			{
				return this._Service;
			}
			set
			{
				if ((this._Service != value))
				{
					this.OnServiceChanging(value);
					this.SendPropertyChanging();
					this._Service = value;
					this.SendPropertyChanged("Service");
					this.OnServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentOnPrice", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PercentOnPrice
		{
			get
			{
				return this._PercentOnPrice;
			}
			set
			{
				if ((this._PercentOnPrice != value))
				{
					this.OnPercentOnPriceChanging(value);
					this.SendPropertyChanging();
					this._PercentOnPrice = value;
					this.SendPropertyChanged("PercentOnPrice");
					this.OnPercentOnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConditionApply", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double ConditionApply
		{
			get
			{
				return this._ConditionApply;
			}
			set
			{
				if ((this._ConditionApply != value))
				{
					this.OnConditionApplyChanging(value);
					this.SendPropertyChanging();
					this._ConditionApply = value;
					this.SendPropertyChanged("ConditionApply");
					this.OnConditionApplyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this.OnZoneChanging(value);
					this.SendPropertyChanging();
					this._Zone = value;
					this.SendPropertyChanged("Zone");
					this.OnZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowIndex", DbType="Int")]
		public System.Nullable<int> RowIndex
		{
			get
			{
				return this._RowIndex;
			}
			set
			{
				if ((this._RowIndex != value))
				{
					this.OnRowIndexChanging(value);
					this.SendPropertyChanging();
					this._RowIndex = value;
					this.SendPropertyChanged("RowIndex");
					this.OnRowIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnIndex", DbType="Int")]
		public System.Nullable<int> ColumnIndex
		{
			get
			{
				return this._ColumnIndex;
			}
			set
			{
				if ((this._ColumnIndex != value))
				{
					this.OnColumnIndexChanging(value);
					this.SendPropertyChanging();
					this._ColumnIndex = value;
					this.SendPropertyChanged("ColumnIndex");
					this.OnColumnIndexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_SpecialCustomer")]
	public partial class SGP_SpecialCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FromPlace;
		
		private string _CGNumber;
		
		private string _SoChungTuThuVe;
		
		private string _SoChungTuLienQuan;
		
		private string _DeliveryDate;
		
		private string _NodeName;
		
		private string _ShiptoAddress;
		
		private string _Province;
		
		private string _Date;
		
		private string _Hour;
		
		private string _Staff;
		
		private string _Note;
		
		private string _Zone;
		
		private string _CustomerID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFromPlaceChanging(string value);
    partial void OnFromPlaceChanged();
    partial void OnCGNumberChanging(string value);
    partial void OnCGNumberChanged();
    partial void OnSoChungTuThuVeChanging(string value);
    partial void OnSoChungTuThuVeChanged();
    partial void OnSoChungTuLienQuanChanging(string value);
    partial void OnSoChungTuLienQuanChanged();
    partial void OnDeliveryDateChanging(string value);
    partial void OnDeliveryDateChanged();
    partial void OnNodeNameChanging(string value);
    partial void OnNodeNameChanged();
    partial void OnShiptoAddressChanging(string value);
    partial void OnShiptoAddressChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnHourChanging(string value);
    partial void OnHourChanged();
    partial void OnStaffChanging(string value);
    partial void OnStaffChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnZoneChanging(string value);
    partial void OnZoneChanged();
    partial void OnCustomerIDChanging(string value);
    partial void OnCustomerIDChanged();
    #endregion
		
		public SGP_SpecialCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromPlace", DbType="NVarChar(50)")]
		public string FromPlace
		{
			get
			{
				return this._FromPlace;
			}
			set
			{
				if ((this._FromPlace != value))
				{
					this.OnFromPlaceChanging(value);
					this.SendPropertyChanging();
					this._FromPlace = value;
					this.SendPropertyChanged("FromPlace");
					this.OnFromPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGNumber", DbType="NVarChar(50)")]
		public string CGNumber
		{
			get
			{
				return this._CGNumber;
			}
			set
			{
				if ((this._CGNumber != value))
				{
					this.OnCGNumberChanging(value);
					this.SendPropertyChanging();
					this._CGNumber = value;
					this.SendPropertyChanged("CGNumber");
					this.OnCGNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoChungTuThuVe", DbType="NVarChar(50)")]
		public string SoChungTuThuVe
		{
			get
			{
				return this._SoChungTuThuVe;
			}
			set
			{
				if ((this._SoChungTuThuVe != value))
				{
					this.OnSoChungTuThuVeChanging(value);
					this.SendPropertyChanging();
					this._SoChungTuThuVe = value;
					this.SendPropertyChanged("SoChungTuThuVe");
					this.OnSoChungTuThuVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoChungTuLienQuan", DbType="NVarChar(50)")]
		public string SoChungTuLienQuan
		{
			get
			{
				return this._SoChungTuLienQuan;
			}
			set
			{
				if ((this._SoChungTuLienQuan != value))
				{
					this.OnSoChungTuLienQuanChanging(value);
					this.SendPropertyChanging();
					this._SoChungTuLienQuan = value;
					this.SendPropertyChanged("SoChungTuLienQuan");
					this.OnSoChungTuLienQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryDate", DbType="NVarChar(50)")]
		public string DeliveryDate
		{
			get
			{
				return this._DeliveryDate;
			}
			set
			{
				if ((this._DeliveryDate != value))
				{
					this.OnDeliveryDateChanging(value);
					this.SendPropertyChanging();
					this._DeliveryDate = value;
					this.SendPropertyChanged("DeliveryDate");
					this.OnDeliveryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="NVarChar(50)")]
		public string NodeName
		{
			get
			{
				return this._NodeName;
			}
			set
			{
				if ((this._NodeName != value))
				{
					this.OnNodeNameChanging(value);
					this.SendPropertyChanging();
					this._NodeName = value;
					this.SendPropertyChanged("NodeName");
					this.OnNodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiptoAddress", DbType="NVarChar(200)")]
		public string ShiptoAddress
		{
			get
			{
				return this._ShiptoAddress;
			}
			set
			{
				if ((this._ShiptoAddress != value))
				{
					this.OnShiptoAddressChanging(value);
					this.SendPropertyChanging();
					this._ShiptoAddress = value;
					this.SendPropertyChanged("ShiptoAddress");
					this.OnShiptoAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(50)")]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hour", DbType="NVarChar(10)")]
		public string Hour
		{
			get
			{
				return this._Hour;
			}
			set
			{
				if ((this._Hour != value))
				{
					this.OnHourChanging(value);
					this.SendPropertyChanging();
					this._Hour = value;
					this.SendPropertyChanged("Hour");
					this.OnHourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff", DbType="NVarChar(100)")]
		public string Staff
		{
			get
			{
				return this._Staff;
			}
			set
			{
				if ((this._Staff != value))
				{
					this.OnStaffChanging(value);
					this.SendPropertyChanging();
					this._Staff = value;
					this.SendPropertyChanged("Staff");
					this.OnStaffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(200)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="NVarChar(50)")]
		public string Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this.OnZoneChanging(value);
					this.SendPropertyChanging();
					this._Zone = value;
					this.SendPropertyChanged("Zone");
					this.OnZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="NVarChar(50)")]
		public string CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_CustomerWithZone")]
	public partial class SGP_CustomerWithZone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ZoneID;
		
		private string _CustomerID;
		
		private string _CustomerName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnZoneIDChanging(string value);
    partial void OnZoneIDChanged();
    partial void OnCustomerIDChanging(string value);
    partial void OnCustomerIDChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    #endregion
		
		public SGP_CustomerWithZone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneID", DbType="NVarChar(50)")]
		public string ZoneID
		{
			get
			{
				return this._ZoneID;
			}
			set
			{
				if ((this._ZoneID != value))
				{
					this.OnZoneIDChanging(value);
					this.SendPropertyChanging();
					this._ZoneID = value;
					this.SendPropertyChanged("ZoneID");
					this.OnZoneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="NVarChar(50)")]
		public string CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(50)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_ChiTietHoaDon")]
	public partial class SGP_ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CGNumber;
		
		private string _PackageName;
		
		private System.Nullable<int> _CuocDV;
		
		private System.Nullable<int> _VAT;
		
		private System.Nullable<int> _Total;
		
		private string _SoCT;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCGNumberChanging(string value);
    partial void OnCGNumberChanged();
    partial void OnPackageNameChanging(string value);
    partial void OnPackageNameChanged();
    partial void OnCuocDVChanging(System.Nullable<int> value);
    partial void OnCuocDVChanged();
    partial void OnVATChanging(System.Nullable<int> value);
    partial void OnVATChanged();
    partial void OnTotalChanging(System.Nullable<int> value);
    partial void OnTotalChanged();
    partial void OnSoCTChanging(string value);
    partial void OnSoCTChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
		
		public SGP_ChiTietHoaDon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGNumber", DbType="NVarChar(50)")]
		public string CGNumber
		{
			get
			{
				return this._CGNumber;
			}
			set
			{
				if ((this._CGNumber != value))
				{
					this.OnCGNumberChanging(value);
					this.SendPropertyChanging();
					this._CGNumber = value;
					this.SendPropertyChanged("CGNumber");
					this.OnCGNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageName", DbType="NVarChar(50)")]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this.OnPackageNameChanging(value);
					this.SendPropertyChanging();
					this._PackageName = value;
					this.SendPropertyChanged("PackageName");
					this.OnPackageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocDV", DbType="Int")]
		public System.Nullable<int> CuocDV
		{
			get
			{
				return this._CuocDV;
			}
			set
			{
				if ((this._CuocDV != value))
				{
					this.OnCuocDVChanging(value);
					this.SendPropertyChanging();
					this._CuocDV = value;
					this.SendPropertyChanged("CuocDV");
					this.OnCuocDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="Int")]
		public System.Nullable<int> VAT
		{
			get
			{
				return this._VAT;
			}
			set
			{
				if ((this._VAT != value))
				{
					this.OnVATChanging(value);
					this.SendPropertyChanging();
					this._VAT = value;
					this.SendPropertyChanged("VAT");
					this.OnVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCT", DbType="NVarChar(50)")]
		public string SoCT
		{
			get
			{
				return this._SoCT;
			}
			set
			{
				if ((this._SoCT != value))
				{
					this.OnSoCTChanging(value);
					this.SendPropertyChanging();
					this._SoCT = value;
					this.SendPropertyChanged("SoCT");
					this.OnSoCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_HoaDon")]
	public partial class SGP_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SoCT;
		
		private string _InvoiceNumber;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSoCTChanging(string value);
    partial void OnSoCTChanged();
    partial void OnInvoiceNumberChanging(string value);
    partial void OnInvoiceNumberChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
		
		public SGP_HoaDon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCT", DbType="NVarChar(50)")]
		public string SoCT
		{
			get
			{
				return this._SoCT;
			}
			set
			{
				if ((this._SoCT != value))
				{
					this.OnSoCTChanging(value);
					this.SendPropertyChanging();
					this._SoCT = value;
					this.SendPropertyChanged("SoCT");
					this.OnSoCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(50)")]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this.OnInvoiceNumberChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNumber = value;
					this.SendPropertyChanged("InvoiceNumber");
					this.OnInvoiceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_CutomerGroups")]
	public partial class SGP_CutomerGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GroupID;
		
		private string _GroupName;
		
		private string _Address;
		
		private string _Phone;
		
		private string _TaxCode;
		
		private string _ZoneID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIDChanging(string value);
    partial void OnGroupIDChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnTaxCodeChanging(string value);
    partial void OnTaxCodeChanged();
    partial void OnZoneIDChanging(string value);
    partial void OnZoneIDChanged();
    #endregion
		
		public SGP_CutomerGroup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(110)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(50)")]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this.OnTaxCodeChanging(value);
					this.SendPropertyChanging();
					this._TaxCode = value;
					this.SendPropertyChanged("TaxCode");
					this.OnTaxCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneID", DbType="NVarChar(5)")]
		public string ZoneID
		{
			get
			{
				return this._ZoneID;
			}
			set
			{
				if ((this._ZoneID != value))
				{
					this.OnZoneIDChanging(value);
					this.SendPropertyChanging();
					this._ZoneID = value;
					this.SendPropertyChanged("ZoneID");
					this.OnZoneIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGP_CustomerGroupDetails")]
	public partial class SGP_CustomerGroupDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustomerID;
		
		private string _GroupID;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIDChanging(string value);
    partial void OnCustomerIDChanged();
    partial void OnGroupIDChanging(string value);
    partial void OnGroupIDChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public SGP_CustomerGroupDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
