<?xml version="1.0" encoding="utf-8"?><Database Name="PMSSGP_200911" Class="SGPMainDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.0.10.10;Initial Catalog=PMSSGP_200911;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PMSSGP_200911ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UMS_tblUserAccount" Member="UMS_tblUserAccounts">
    <Type Name="UMS_tblUserAccount">
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserGroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FValid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FGroup" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FAdm" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FSpv" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(240)" CanBeNull="true" />
      <Column Name="CantChangePwd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PwdNeverExpire" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MustChangePwd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateOfChangePwd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MemberOf" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="UMS_tblUserAccount_UMS_tblUserAccountPostOffice" Member="UMS_tblUserAccountPostOffices" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="UMS_tblUserAccountPostOffice" />
    </Type>
  </Table>
  <Table Name="dbo.UMS_tblUserAccountPostOffice" Member="UMS_tblUserAccountPostOffices">
    <Type Name="UMS_tblUserAccountPostOffice">
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PostOfficeID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="UMS_tblUserAccount_UMS_tblUserAccountPostOffice" Member="UMS_tblUserAccount" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="UMS_tblUserAccount" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BS_Provinces" Member="BS_Provinces">
    <Type Name="BS_Province">
      <Column Name="ProvinceID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProvinceName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CountryID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BS_Province_MM_Mailer" Member="MM_Mailers" ThisKey="ProvinceID" OtherKey="RecieverProvinceID" Type="MM_Mailer" />
      <Association Name="BS_Province_BS_District" Member="BS_Districts" ThisKey="ProvinceID" OtherKey="ProvinceID" Type="BS_District" />
    </Type>
  </Table>
  <Table Name="dbo.MM_ServiceTypes" Member="MM_ServiceTypes">
    <Type Name="MM_ServiceType">
      <Column Name="ServiceTypeID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OutsideLine" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PriceType" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MM_ServiceType_MM_Mailer" Member="MM_Mailers" ThisKey="ServiceTypeID" OtherKey="ServiceTypeID" Type="MM_Mailer" />
    </Type>
  </Table>
  <Table Name="dbo.MM_Customers" Member="MM_Customers">
    <Type Name="MM_Customer">
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerGroupID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ProvinceID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CountryID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="FaxNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CompanyPhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PersonalInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PostOfficeID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DebtDayInMonth" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MemberOf" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DebitObjectID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="MM_Customer_MM_Mailer" Member="MM_Mailers" ThisKey="CustomerID" OtherKey="SenderID" Type="MM_Mailer" />
    </Type>
  </Table>
  <Table Name="dbo.MM_MailerDeliveryDetail" Member="MM_MailerDeliveryDetails">
    <Type Name="MM_MailerDeliveryDetail">
      <Column Name="DocumentID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MailerID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IsDeliverOver" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeliveryTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeliveryStatus" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PaymentFinished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeliveryNotes" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ConfirmDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmUserID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ConfirmIndex" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReturnReasonID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SyncFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastSyncDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MM_Mailer_MM_MailerDeliveryDetail" Member="MM_Mailer" ThisKey="MailerID" OtherKey="MailerID" Type="MM_Mailer" IsForeignKey="true" />
      <Association Name="MM_Mailer_MM_MailerDeliveryDetail1" Member="MM_Mailer1" ThisKey="MailerID" OtherKey="MailerID" Type="MM_Mailer" IsForeignKey="true" />
      <Association Name="MM_MailerDelivery_MM_MailerDeliveryDetail" Member="MM_MailerDelivery" ThisKey="DocumentID" OtherKey="DocumentID" Type="MM_MailerDelivery" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MM_Mailers" Member="MM_Mailers">
    <Type Name="MM_Mailer">
      <Column Name="AcceptDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AcceptTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MailerID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SenderID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SenderRepresenterID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SenderName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SenderAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SenderPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SenderCountryID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SenderProvinceID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SenderDistrictID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RecieverID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RecieverRepresenterID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RecieverName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RecieverAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RecieverPhone" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="RecieverCountryID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RecieverProvinceID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="RecieverDistrictID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ServiceTypeID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="MailerTypeID" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RealWeight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Money" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PriceDefault" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PriceService" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="BefVATAmount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="VATPercent" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="VATAmount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="AmountBefDiscount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PostOfficeAcceptID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentMethodID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PostOfficeRecieverMoneyID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MailerDescription" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThirdpartyDocID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ThirdpartyCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ThirdpartyPaymentMethodID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ParentMailerID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastUserGroupID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentStatusID" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CurrentPostOfficeID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocIndex" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="RangeWeightID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RangeDistanceID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PriceType" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PriceIncludeVAT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CommissionAmt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CommissionPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CostAmt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SalesClosingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RecieverAddressNbr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveProvinceID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DiscountPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LastUpdDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="RecordState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SyncFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastSyncDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amt4Comm" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LastUpdStatusTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MM_Mailer_MM_MailerDeliveryDetail" Member="MM_MailerDeliveryDetails" ThisKey="MailerID" OtherKey="MailerID" Type="MM_MailerDeliveryDetail" />
      <Association Name="MM_Mailer_MM_MailerDeliveryDetail1" Member="MM_MailerDeliveryDetails1" ThisKey="MailerID" OtherKey="MailerID" Type="MM_MailerDeliveryDetail" />
      <Association Name="MM_Mailer_MM_PackingListInternalDetail" Member="MM_PackingListInternalDetails" ThisKey="MailerID" OtherKey="MailerID" Type="MM_PackingListInternalDetail" />
      <Association Name="BS_Province_MM_Mailer" Member="BS_Province" ThisKey="RecieverProvinceID" OtherKey="ProvinceID" Type="BS_Province" IsForeignKey="true" />
      <Association Name="MM_Customer_MM_Mailer" Member="MM_Customer" ThisKey="SenderID" OtherKey="CustomerID" Type="MM_Customer" IsForeignKey="true" />
      <Association Name="MM_ServiceType_MM_Mailer" Member="MM_ServiceType" ThisKey="ServiceTypeID" OtherKey="ServiceTypeID" Type="MM_ServiceType" IsForeignKey="true" />
      <Association Name="MM_Status_MM_Mailer" Member="MM_Status" ThisKey="CurrentStatusID" OtherKey="StatusID" Type="MM_Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MM_PackingListInternalDetail" Member="MM_PackingListInternalDetails">
    <Type Name="MM_PackingListInternalDetail">
      <Column Name="DocumentID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MailerID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Accept" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SendNotes" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AcceptNotes" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AcceptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SyncFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastSyncDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MM_Mailer_MM_PackingListInternalDetail" Member="MM_Mailer" ThisKey="MailerID" OtherKey="MailerID" Type="MM_Mailer" IsForeignKey="true" />
      <Association Name="MM_PackingListInternal_MM_PackingListInternalDetail" Member="MM_PackingListInternal" ThisKey="DocumentID" OtherKey="DocumentID" Type="MM_PackingListInternal" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MM_PackingListInternal" Member="MM_PackingListInternals">
    <Type Name="MM_PackingListInternal">
      <Column Name="DocumentID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DocumentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocumentTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PostOfficeID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PostOfficeIDAccept" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NumberOfPackage" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TripNumber" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ArrivedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TransportObjectID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SendDescription" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AcceptDescription" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PackingListStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MailerType" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="UserGroupSend" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserGroupAccept" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AcceptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmployeeSend" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EmployeeAccept" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserGroupLastModified" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="RecordState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SyncFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastSyncDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MM_PackingListInternal_MM_PackingListInternalDetail" Member="MM_PackingListInternalDetails" ThisKey="DocumentID" OtherKey="DocumentID" Type="MM_PackingListInternalDetail" />
    </Type>
  </Table>
  <Table Name="dbo.MM_MailerDelivery" Member="MM_MailerDeliveries">
    <Type Name="MM_MailerDelivery">
      <Column Name="DocumentID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TripNumber" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DocumentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocumentTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PostOfficeID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MailerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberOfPackage" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastUpdDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="RecordState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SyncFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastSyncDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MM_MailerDelivery_MM_MailerDeliveryDetail" Member="MM_MailerDeliveryDetails" ThisKey="DocumentID" OtherKey="DocumentID" Type="MM_MailerDeliveryDetail" />
      <Association Name="BS_Employee_MM_MailerDelivery" Member="BS_Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="BS_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BS_Employees" Member="BS_Employees">
    <Type Name="BS_Employee">
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PostOfficeID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="FaxNo" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MemberOf" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProvinceID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="IsCollaborators" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SGPEmployeeID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Imei" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="BS_Employee_MM_MailerDelivery" Member="MM_MailerDeliveries" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="MM_MailerDelivery" />
    </Type>
  </Table>
  <Table Name="dbo.MM_Status" Member="MM_Status">
    <Type Name="MM_Status">
      <Column Name="StatusID" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StatusName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MM_Status_MM_Mailer" Member="MM_Mailers" ThisKey="StatusID" OtherKey="CurrentStatusID" Type="MM_Mailer" />
    </Type>
  </Table>
  <Table Name="dbo.MM_ReturnReason" Member="MM_ReturnReasons">
    <Type Name="MM_ReturnReason">
      <Column Name="ReturnReasonID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReturnReasonName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BS_Districts" Member="BS_Districts">
    <Type Name="BS_District">
      <Column Name="DistrictID" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProvinceID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BS_Province_BS_District" Member="BS_Province" ThisKey="ProvinceID" OtherKey="ProvinceID" Type="BS_Province" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGP_ChiPhi" Member="SGP_ChiPhis">
    <Type Name="SGP_ChiPhi">
      <Column Name="ctvphat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="cg" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="tl" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="loaihang" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="noiden" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cptt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cpnt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bcchapnhan" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="khachhang" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="cuocchinh" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="phuphi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="quan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngaynhan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bcnhap" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>