//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintCG_24062016.SGPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGPService.ISGPService")]
    public interface ISGPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISGPService/login", ReplyAction="http://tempuri.org/ISGPService/loginResponse")]
        bool login(string user, string pass, string post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISGPService/getmaxMailerID", ReplyAction="http://tempuri.org/ISGPService/getmaxMailerIDResponse")]
        string getmaxMailerID(string postoffice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISGPServiceChannel : PrintCG_24062016.SGPService.ISGPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SGPServiceClient : System.ServiceModel.ClientBase<PrintCG_24062016.SGPService.ISGPService>, PrintCG_24062016.SGPService.ISGPService {
        
        public SGPServiceClient() {
        }
        
        public SGPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SGPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SGPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SGPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool login(string user, string pass, string post) {
            return base.Channel.login(user, pass, post);
        }
        
        public string getmaxMailerID(string postoffice) {
            return base.Channel.getmaxMailerID(postoffice);
        }
    }
}
