//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintCG_24062016.ChuyenThu {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChuyenThu.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetEmployees(string postofficeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetUserLogin(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPostOfice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetUserPostOfice(string UserID, string PostOffice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string InsertHistory(string MailerID, string PostOfficeID, string DocumentID, string UserGroupID, int Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetMailerDelivery(string PostOfficeID, string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetMailerDeliveryDetails(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDetailbyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetMailerDeliveryDetailbyID(string MailerID, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMailerDeliveryDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string InsertMailerDeliveryDetail(string DocumentID, string MailerID, string Notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMailerDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string UpdateMailerDelivery(string DocumentID, int MailerCount, int Quantity, double Weight, double NumberOfPackage, string UserGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetMailerCustomer(string FromDate, string ToDate, string PostOfficeID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int SGP_PDA_Login(string UserID, string Password, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_MailerDeliveryInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SGP_MailerDeliveryInsert(string DocumentID, string PostOfficeID, string EmployeeID, string Description, int NumberOfPackage, string UserGroupID, double MailerCount, double Quantity, double Weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_MaxMailerDeliveryDocumentID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SGP_MaxMailerDeliveryDocumentID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_DeleteMailerDeliveryDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SGP_DeleteMailerDeliveryDetail(string DocumentID, string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CheckMailerDeliveryDocumentID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SGP_CheckMailerDeliveryDocumentID(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CG8_Employee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet SGP_CG8_Employee(string FromDate, string ToDate, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CG8_EmployeeDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet SGP_CG8_EmployeeDetail(string FromDate, string ToDate, string Employee);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : PrintCG_24062016.ChuyenThu.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<PrintCG_24062016.ChuyenThu.Service1Soap>, PrintCG_24062016.ChuyenThu.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetEmployees(string postofficeid) {
            return base.Channel.GetEmployees(postofficeid);
        }
        
        public System.Data.DataSet GetUserLogin(string UserID) {
            return base.Channel.GetUserLogin(UserID);
        }
        
        public System.Data.DataSet GetUserPostOfice(string UserID, string PostOffice) {
            return base.Channel.GetUserPostOfice(UserID, PostOffice);
        }
        
        public string InsertHistory(string MailerID, string PostOfficeID, string DocumentID, string UserGroupID, int Status) {
            return base.Channel.InsertHistory(MailerID, PostOfficeID, DocumentID, UserGroupID, Status);
        }
        
        public System.Data.DataSet GetMailerDelivery(string PostOfficeID, string FromDate, string ToDate) {
            return base.Channel.GetMailerDelivery(PostOfficeID, FromDate, ToDate);
        }
        
        public System.Data.DataSet GetMailerDeliveryDetails(string DocumentID) {
            return base.Channel.GetMailerDeliveryDetails(DocumentID);
        }
        
        public System.Data.DataSet GetMailerDeliveryDetailbyID(string MailerID, string PostOfficeID) {
            return base.Channel.GetMailerDeliveryDetailbyID(MailerID, PostOfficeID);
        }
        
        public string InsertMailerDeliveryDetail(string DocumentID, string MailerID, string Notes) {
            return base.Channel.InsertMailerDeliveryDetail(DocumentID, MailerID, Notes);
        }
        
        public string UpdateMailerDelivery(string DocumentID, int MailerCount, int Quantity, double Weight, double NumberOfPackage, string UserGroupID) {
            return base.Channel.UpdateMailerDelivery(DocumentID, MailerCount, Quantity, Weight, NumberOfPackage, UserGroupID);
        }
        
        public System.Data.DataSet GetMailerCustomer(string FromDate, string ToDate, string PostOfficeID, string CustomerID) {
            return base.Channel.GetMailerCustomer(FromDate, ToDate, PostOfficeID, CustomerID);
        }
        
        public int SGP_PDA_Login(string UserID, string Password, string PostOfficeID) {
            return base.Channel.SGP_PDA_Login(UserID, Password, PostOfficeID);
        }
        
        public string SGP_MailerDeliveryInsert(string DocumentID, string PostOfficeID, string EmployeeID, string Description, int NumberOfPackage, string UserGroupID, double MailerCount, double Quantity, double Weight) {
            return base.Channel.SGP_MailerDeliveryInsert(DocumentID, PostOfficeID, EmployeeID, Description, NumberOfPackage, UserGroupID, MailerCount, Quantity, Weight);
        }
        
        public string SGP_MaxMailerDeliveryDocumentID() {
            return base.Channel.SGP_MaxMailerDeliveryDocumentID();
        }
        
        public string SGP_DeleteMailerDeliveryDetail(string DocumentID, string MailerID) {
            return base.Channel.SGP_DeleteMailerDeliveryDetail(DocumentID, MailerID);
        }
        
        public string SGP_CheckMailerDeliveryDocumentID(string DocumentID) {
            return base.Channel.SGP_CheckMailerDeliveryDocumentID(DocumentID);
        }
        
        public System.Data.DataSet SGP_CG8_Employee(string FromDate, string ToDate, string PostOfficeID) {
            return base.Channel.SGP_CG8_Employee(FromDate, ToDate, PostOfficeID);
        }
        
        public System.Data.DataSet SGP_CG8_EmployeeDetail(string FromDate, string ToDate, string Employee) {
            return base.Channel.SGP_CG8_EmployeeDetail(FromDate, ToDate, Employee);
        }
    }
}
