//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintCG_24062016.BaoCaoSLMsYen {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BaoCaoSLMsYen.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaotuan", ReplyAction="http://tempuri.org/IService1/baocaotuanResponse")]
        System.Data.DataSet baocaotuan(string cs, string postoffice, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaotuanDT", ReplyAction="http://tempuri.org/IService1/baocaotuanDTResponse")]
        System.Data.DataSet baocaotuanDT(string cs, string postoffice, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaotuantong", ReplyAction="http://tempuri.org/IService1/baocaotuantongResponse")]
        System.Data.DataSet baocaotuantong(string cs, string postoffice, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaotuantongDT", ReplyAction="http://tempuri.org/IService1/baocaotuantongDTResponse")]
        System.Data.DataSet baocaotuantongDT(string cs, string postoffice, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaothangctv", ReplyAction="http://tempuri.org/IService1/baocaothangctvResponse")]
        System.Data.DataSet baocaothangctv(string cs, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaothangctvDT", ReplyAction="http://tempuri.org/IService1/baocaothangctvDTResponse")]
        System.Data.DataSet baocaothangctvDT(string cs, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaothang", ReplyAction="http://tempuri.org/IService1/baocaothangResponse")]
        System.Data.DataSet baocaothang(string cs, string postoffice, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaothangDT", ReplyAction="http://tempuri.org/IService1/baocaothangDTResponse")]
        System.Data.DataSet baocaothangDT(string cs, string postoffice, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaotuantongctv", ReplyAction="http://tempuri.org/IService1/baocaotuantongctvResponse")]
        System.Data.DataSet baocaotuantongctv(string cs, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/baocaotuantongctvDT", ReplyAction="http://tempuri.org/IService1/baocaotuantongctvDTResponse")]
        System.Data.DataSet baocaotuantongctvDT(string cs, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/connectionString", ReplyAction="http://tempuri.org/IService1/connectionStringResponse")]
        string connectionString(int check);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PrintCG_24062016.BaoCaoSLMsYen.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PrintCG_24062016.BaoCaoSLMsYen.IService1>, PrintCG_24062016.BaoCaoSLMsYen.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet baocaotuan(string cs, string postoffice, string fromdate, string todate) {
            return base.Channel.baocaotuan(cs, postoffice, fromdate, todate);
        }
        
        public System.Data.DataSet baocaotuanDT(string cs, string postoffice, string fromdate, string todate) {
            return base.Channel.baocaotuanDT(cs, postoffice, fromdate, todate);
        }
        
        public System.Data.DataSet baocaotuantong(string cs, string postoffice, string fromdate, string todate) {
            return base.Channel.baocaotuantong(cs, postoffice, fromdate, todate);
        }
        
        public System.Data.DataSet baocaotuantongDT(string cs, string postoffice, string fromdate, string todate) {
            return base.Channel.baocaotuantongDT(cs, postoffice, fromdate, todate);
        }
        
        public System.Data.DataSet baocaothangctv(string cs, string fromdate, string todate) {
            return base.Channel.baocaothangctv(cs, fromdate, todate);
        }
        
        public System.Data.DataSet baocaothangctvDT(string cs, string fromdate, string todate) {
            return base.Channel.baocaothangctvDT(cs, fromdate, todate);
        }
        
        public System.Data.DataSet baocaothang(string cs, string postoffice, string fromdate, string todate) {
            return base.Channel.baocaothang(cs, postoffice, fromdate, todate);
        }
        
        public System.Data.DataSet baocaothangDT(string cs, string postoffice, string fromdate, string todate) {
            return base.Channel.baocaothangDT(cs, postoffice, fromdate, todate);
        }
        
        public System.Data.DataSet baocaotuantongctv(string cs, string fromdate, string todate) {
            return base.Channel.baocaotuantongctv(cs, fromdate, todate);
        }
        
        public System.Data.DataSet baocaotuantongctvDT(string cs, string fromdate, string todate) {
            return base.Channel.baocaotuantongctvDT(cs, fromdate, todate);
        }
        
        public string connectionString(int check) {
            return base.Channel.connectionString(check);
        }
    }
}
